name: 'crypto_trading'
version: '1.0.0'

profile: 'crypto_trading'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_trading:               # odpovídá složce models/crypto_trading/
    +materialized: view         # výchozí nastavení, lze přepsat níž

    silver:                     # odpovídá složce models/crypto_trading/silver/
      +schema: SILVER
      +materialized: view

    gold:                       # odpovídá složce models/crypto_trading/gold/
      +schema: GOLD
      +materialized: view

    example:
      +enabled: false
